name: Go

on: [push]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.23.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        with:
          path: '.'
          run: go install github.com/TimoKats/mdrss@latest &&
             mdrss --config .mdrss/config.json update

