name: Markdown to XML Conversion

on:
  push:
    branches:
      - main  # Change this to your default branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use a compatible Node.js version

    - name: Install dependencies
      run: |
        npm install marked xml2js

    - name: Convert Markdown to XML
      run: |
        # Create the 'xml' directory if it doesn't exist
        mkdir -p xml

        # Initialize an empty XML root
        xmlContent="<posts>"

        # Loop through all markdown files in 'posts' directory
        for file in posts/*.md; do
          # Read the markdown content
          markdownContent=$(cat $file)

          # Extract the title (first line in Markdown, typically a # header)
          title=$(echo "$markdownContent" | head -n 1 | sed 's/^# //')

          # Convert Markdown to HTML using marked
          htmlContent=$(echo "$markdownContent" | npx marked)

          # Append this post’s XML content to the main XML structure
          xmlContent="$xmlContent<post><title>$title</title><content>$htmlContent</content></post>"
        done

        # Close the XML root tag
        xmlContent="$xmlContent</posts>"

        # Write the final XML content to index.xml
        echo "$xmlContent" > xml/index.xml

    - name: Commit and push XML file
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add xml/index.xml
        git commit -m "Generate index.xml with all posts"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
